# Generated by Django 6.0.3 on 2026-04-14 11:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_method', models.CharField(choices=[('call', 'Звонок'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('max', 'Max'), ('email', 'Email')], default='call', max_length=20, verbose_name='Предпочитаемый способ связи')),
                ('email', models.EmailField(blank=True, help_text='Укажите email, если предпочитаете связь по почте', max_length=254, verbose_name='Email')),
                ('num_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество человек')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('completed', 'Выполнен')], default='new', max_length=20, verbose_name='Статус')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='excursions.excursion', verbose_name='Экскурсия')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='excursions.slot', verbose_name='Слот')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ на экскурсию',
                'verbose_name_plural': 'Заказы на экскурсии',
                'ordering': ['-created_at'],
            },
        ),
    ]
