# Generated by Django 6.0.4 on 2026-04-26 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('excursions', '0002_alter_category_description_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourorder',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Отчество клиента', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительная информация от клиента', verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='contact_method',
            field=models.CharField(choices=[('call', 'Звонок'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('max', 'Max'), ('email', 'Email')], default='call', help_text='Как с вами связаться для подтверждения заказа', max_length=20, verbose_name='Предпочитаемый способ связи'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='excursion',
            field=models.ForeignKey(help_text='Экскурсия, на которую оформлен заказ', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='excursions.excursion', verbose_name='Экскурсия'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='first_name',
            field=models.CharField(help_text='Имя клиента', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия клиента', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='manager_comment',
            field=models.TextField(blank=True, help_text='Внутренний комментарий для менеджеров', verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='num_participants',
            field=models.PositiveIntegerField(help_text='Количество участников экскурсии', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='phone',
            field=models.CharField(help_text='Контактный номер телефона клиента', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='slot',
            field=models.ForeignKey(help_text='Временной слот для проведения экскурсии', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='excursions.slot', verbose_name='Слот'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('completed', 'Выполнен')], default='new', help_text='Текущий статус заказа', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления заказа', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, сделавший заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='tourorder',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='at_least_one_contact_field_filled', violation_error_message='Хотя бы одно из полей (телефон или email) должно быть заполнено'),
        ),
    ]
