# Generated by Django 6.0.3 on 2026-03-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='location_type',
            field=models.CharField(choices=[('city', 'Городские экскурсии'), ('suburban', 'Загородные экскурсии'), ('russia', 'Туры по России')], db_index=True, default='city', max_length=20, verbose_name='Тип локации'),
        ),
    ]
