# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexcursion',
            name='rating',
        ),
    ]
