# Generated by Django 6.0.4 on 2026-04-20 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание категории', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории экскурсий', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-совместимое название категории', max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='category',
            field=models.ForeignKey(help_text='Категория, к которой относится экскурсия', on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='excursions.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания экскурсии', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='description',
            field=models.TextField(help_text='Подробное описание экскурсии', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='duration',
            field=models.PositiveIntegerField(help_text='Продолжительность экскурсии в минутах', verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Доступна ли экскурсия для бронирования', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='location_type',
            field=models.CharField(choices=[('city', 'Городские экскурсии'), ('suburban', 'Загородные экскурсии'), ('russia', 'Туры по России')], db_index=True, default='city', help_text='Тип местоположения проведения экскурсии', max_length=20, verbose_name='Тип локации'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Минимальная цена участия в экскурсии', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от (руб)'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='short_description',
            field=models.TextField(help_text='Краткое описание экскурсии для превью', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-совместимое название экскурсии', max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='title',
            field=models.CharField(help_text='Название экскурсии', max_length=200, verbose_name='Название экскурсии'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления экскурсии', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='excursionimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Альтернативный текст для изображения', max_length=200, verbose_name='Alt-текст'),
        ),
        migrations.AlterField(
            model_name='excursionimage',
            name='excursion',
            field=models.ForeignKey(help_text='Экскурсия, к которой относится изображение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excursions.excursion', verbose_name='Экскурсия'),
        ),
        migrations.AlterField(
            model_name='excursionimage',
            name='image',
            field=models.ImageField(help_text='Фотография экскурсии', upload_to='excursions/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='excursionimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Является ли изображение главным для экскурсии', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='booked_participants',
            field=models.PositiveIntegerField(default=0, help_text='Количество забронированных мест', verbose_name='Забронировано'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(help_text='Дата проведения экскурсии', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='excursion',
            field=models.ForeignKey(help_text='Экскурсия, для которой создан слот', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='excursions.excursion', verbose_name='Экскурсия'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='max_participants',
            field=models.PositiveIntegerField(default=20, help_text='Максимальное количество участников', verbose_name='Макс. человек'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Особая цена для этого слота, если отличается от базовой', max_digits=10, null=True, verbose_name='Цена для этого слота (если отличается)'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='time',
            field=models.TimeField(help_text='Время начала проведения экскурсии', verbose_name='Время начала'),
        ),
    ]
