# Generated by Django 5.2.15 on 2026-07-18 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0004_add_program_days_and_ticket_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionprogramday',
            name='excursion',
            field=models.ForeignKey(
                help_text='Экскурсия, к которой относится день программы',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='program_days',
                to='excursions.excursion',
                verbose_name='Экскурсия',
            ),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='excursion',
            field=models.ForeignKey(
                help_text='Экскурсия, к которой относится тип билета',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ticket_types',
                to='excursions.excursion',
                verbose_name='Экскурсия',
            ),
        ),
    ]
