# Generated by Django 6.0.4 on 2026-04-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_toxic',
            field=models.BooleanField(default=False, verbose_name='Содержит нецензурную лексику'),
        ),
        migrations.AddField(
            model_name='review',
            name='toxicity_score',
            field=models.FloatField(default=0.0, verbose_name='Степень токсичности'),
        ),
    ]
