# Generated by Django 6.0.4 on 2026-05-14 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_tourorder_middle_name_alter_tourorder_comment_and_more'),
        ('excursions', '0002_alter_category_description_alter_category_name_and_more'),
        ('reviews', '0002_review_is_toxic_review_toxicity_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фото к отзыву', 'verbose_name_plural': 'Фото к отзывам'},
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания отзыва', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='excursion',
            field=models.ForeignKey(help_text='Экскурсия, на которую оставлен отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='excursions.excursion', verbose_name='Экскурсия'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_toxic',
            field=models.BooleanField(default=False, help_text='Определяет, содержит ли отзыв нецензурную лексику', verbose_name='Содержит нецензурную лексику'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderator_comment',
            field=models.TextField(blank=True, help_text='Комментарий оставленный модератором при обработке отзыва', verbose_name='Комментарий модератора'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Заказ, по которому оставлен отзыв', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.tourorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка экскурсии от 1 до 5 звезд', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', help_text='Текущий статус модерации отзыва', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Текст отзыва на экскурсию', max_length=2000, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='toxicity_score',
            field=models.FloatField(default=0.0, help_text='Количественная оценка токсичности текста отзыва', verbose_name='Степень токсичности'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления отзыва', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='Автор отзыва', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(help_text='Фотография к отзыву', upload_to='reviews/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(help_text='Отзыв, к которому относится изображение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время загрузки изображения', verbose_name='Дата загрузки'),
        ),
    ]
