# Generated by Django 5.2.15 on 2026-06-07 13:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории экскурсий', max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='URL-совместимое название категории', max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Подробное описание категории', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='user', max_length=15)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.client')),
            ],
        ),
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('people_count', models.IntegerField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_state', to='assistant.client')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.dialogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название экскурсии', max_length=200, verbose_name='Название экскурсии')),
                ('slug', models.SlugField(blank=True, help_text='URL-совместимое название экскурсии', max_length=250, unique=True, verbose_name='Slug')),
                ('location_type', models.CharField(choices=[('city', 'Городские экскурсии'), ('suburban', 'Загородные экскурсии'), ('russia', 'Туры по России')], db_index=True, default='city', help_text='Тип местоположения проведения экскурсии', max_length=20, verbose_name='Тип локации')),
                ('description', models.TextField(help_text='Подробное описание экскурсии', verbose_name='Полное описание')),
                ('short_description', models.TextField(help_text='Краткое описание экскурсии для превью', max_length=500, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Минимальная цена участия в экскурсии', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от (руб)')),
                ('duration', models.PositiveIntegerField(help_text='Продолжительность экскурсии в минутах', verbose_name='Длительность (мин)')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли экскурсия для бронирования', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания экскурсии', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления экскурсии', verbose_name='Дата обновления')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится экскурсия', on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='assistant.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Фотография экскурсии', upload_to='excursions/%Y/%m/%d/', verbose_name='Фото')),
                ('alt_text', models.CharField(blank=True, help_text='Альтернативный текст для изображения', max_length=200, verbose_name='Alt-текст')),
                ('is_main', models.BooleanField(default=False, help_text='Является ли изображение главным для экскурсии', verbose_name='Главное фото')),
                ('excursion', models.ForeignKey(help_text='Экскурсия, к которой относится изображение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assistant.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Фото экскурсии',
                'verbose_name_plural': 'Фото экскурсий',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('closed', 'Closed')], default='new', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.client')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.excursion')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата проведения экскурсии', verbose_name='Дата')),
                ('time', models.TimeField(help_text='Время начала проведения экскурсии', verbose_name='Время начала')),
                ('max_participants', models.PositiveIntegerField(default=20, help_text='Максимальное количество участников', verbose_name='Макс. человек')),
                ('booked_participants', models.PositiveIntegerField(default=0, help_text='Количество забронированных мест', verbose_name='Забронировано')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Особая цена для этого слота, если отличается от базовой', max_digits=10, null=True, verbose_name='Цена для этого слота (если отличается)')),
                ('excursion', models.ForeignKey(help_text='Экскурсия, для которой создан слот', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='assistant.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
                'ordering': ['date', 'time'],
                'unique_together': {('excursion', 'date', 'time')},
            },
        ),
    ]
