# Generated by Django 6.0.4 on 2026-04-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_email_verified_customuser_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Когда было отправлено письмо подтверждения email', null=True, verbose_name='Время отправки подтверждения email'),
        ),
    ]
