# Generated by Django 6.0.4 on 2026-05-06 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursions', '0002_alter_category_description_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Идентификатор сессии для анонимных пользователей', max_length=255, verbose_name='ID сессии')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Общая длительность просмотра в секундах', verbose_name='Длительность просмотра (сек)')),
                ('source', models.CharField(choices=[('search', 'Поиск'), ('catalog', 'Каталог'), ('recommendation', 'Рекомендации'), ('similar', 'Похожие экскурсии'), ('direct', 'Прямой переход')], default='catalog', help_text='Откуда пользователь перешел на страницу экскурсии', max_length=20, verbose_name='Источник перехода')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Время начала просмотра экскурсии', verbose_name='Время начала')),
                ('processed_for_recommendations', models.BooleanField(default=False, help_text='Были ли данные отправлены в систему рекомендаций', verbose_name='Обработано для рекомендаций')),
                ('excursion', models.ForeignKey(help_text='Просмотренная экскурсия', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='excursions.excursion', verbose_name='Экскурсия')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, просмотревший экскурсию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр экскурсии',
                'verbose_name_plural': 'Просмотры экскурсий',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['excursion', 'started_at'], name='analytics_e_excursi_3ad2be_idx'), models.Index(fields=['user', 'started_at'], name='analytics_e_user_id_564307_idx'), models.Index(fields=['session_id', 'started_at'], name='analytics_e_session_a9c906_idx')],
            },
        ),
    ]
