# Generated by Django 6.0.4 on 2026-04-20 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursions', '0002_alter_category_description_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления экскурсии в избранное', verbose_name='Дата добавления')),
                ('excursion', models.ForeignKey(help_text='Экскурсия, добавленная в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='excursions.excursion', verbose_name='Экскурсия')),
                ('user', models.ForeignKey(help_text='Пользователь, добавивший экскурсию в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная экскурсия',
                'verbose_name_plural': 'Избранные экскурсии',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', '-added_at'], name='wishlist_wi_user_id_32273e_idx'), models.Index(fields=['excursion'], name='wishlist_wi_excursi_641231_idx')],
                'unique_together': {('user', 'excursion')},
            },
        ),
    ]
